"""add count column to otder product association table

Revision ID: 79e8cbc76d08
Revises: de3354df82e1
Create Date: 2025-07-01 18:29:33.378954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '79e8cbc76d08'
down_revision: Union[str, Sequence[str], None] = 'de3354df82e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_product_association',
        sa.Column('count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'count')
    # ### end Alembic commands ###
